[package]
name = "ws_subscription"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
serde = "1.0.217"
solana-client = "2.0.21"
solana-sdk = "2.1.7"
solana-transaction-status-client-types= "2.1.7"
tokio = { version = "1.42.0", features = [ "rt-multi-thread", "macros" ] }
